In [1]:
import tensorflow as tf

In [2]:
message = tf.constant('Welcome to the existing world f Deep Neural Networks!')

In [3]:
with tf.Session() as sess:
    print(sess.run(message).decode())

Welcome to the existing world f Deep Neural Networks!


In [4]:
sess = tf.InteractiveSession()
v_1 = tf.constant([1,2,3,4])
v_2 = tf.constant([2,1,5,3])
v_add = tf.add(v_1, v_2)


In [5]:
print(v_add.eval())

[3 3 8 7]


In [6]:
sess.close()

In [7]:
t_1 = tf.constant(4)
t_2 = tf.constant([4,3,2])
t_random = tf.random_normal([2,3], mean=2.0, stddev=4, seed=12)

In [8]:
t_random

<tf.Tensor 'random_normal:0' shape=(2, 3) dtype=float32>

In [9]:
t_random = tf.truncated_normal([1,5], stddev=2, seed=12)

In [10]:
sess = tf.InteractiveSession()
#Define a 5x5 Identity matrix

I_matrix = tf.eye(5)
print(I_matrix.eval())

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
X = tf.Variable(tf.eye(10))
X.initializer.run()
print(X.eval())

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [14]:
A = tf.Variable(tf.random_normal([5,10]))
A.initializer.run()
print(A.eval())


[[-0.525729   -1.5633048   0.7489659  -1.283794    0.03218996 -0.9629391
  -1.1636349   0.5961815   1.1969652   1.3774494 ]
 [-0.23335148 -0.6498845  -0.11658292  0.23202398  1.2185732   0.48592362
   0.23427106 -0.43399215 -0.59318495 -0.44777185]
 [-0.25994673 -1.0270928  -0.02158686 -1.6712426   0.89542514  0.17528145
   0.45552802  0.06737176 -1.1433682   0.59410775]
 [ 0.90171504 -1.1686602   0.6205999  -0.5491025  -0.92854846 -0.05149506
   0.2085381  -1.0828903   0.34127975 -0.5502693 ]
 [ 0.8547978   1.7632552  -0.6391838   0.03278199 -0.31179222  0.06680597
   0.1787957  -0.12890258 -0.5766933   1.6141087 ]]


In [15]:
# Multiply two matrices
product = tf.matmul(A, X)
print(product.eval())

[[-0.525729   -1.5633048   0.7489659  -1.283794    0.03218996 -0.9629391
  -1.1636349   0.5961815   1.1969652   1.3774494 ]
 [-0.23335148 -0.6498845  -0.11658292  0.23202398  1.2185732   0.48592362
   0.23427106 -0.43399215 -0.59318495 -0.44777185]
 [-0.25994673 -1.0270928  -0.02158686 -1.6712426   0.89542514  0.17528145
   0.45552802  0.06737176 -1.1433682   0.59410775]
 [ 0.90171504 -1.1686602   0.6205999  -0.5491025  -0.92854846 -0.05149506
   0.2085381  -1.0828903   0.34127975 -0.5502693 ]
 [ 0.8547978   1.7632552  -0.6391838   0.03278199 -0.31179222  0.06680597
   0.1787957  -0.12890258 -0.5766933   1.6141087 ]]


In [16]:
#
#


In [24]:
# Create two random matrices
a = tf.Variable(tf.random_normal([4,5], stddev=2))
b = tf.Variable(tf.random_normal([4,5], stddev=2))
a.initializer.run()
b.initializer.run()
print(a.eval(), '-\n-\n', b.eval())

[[-3.429333    0.5499375   1.8460882  -0.12752831 -0.23299508]
 [-2.7435646   3.01775    -0.98947436 -0.04431289 -1.2755423 ]
 [-0.39203596 -1.0892094   4.1074924  -2.967633    2.5527658 ]
 [ 1.839403    0.569957    1.9062077  -1.5755415   2.1328313 ]] -
-
 [[ 0.3497081   1.8146939   3.1546597   3.3776622  -1.1485372 ]
 [ 1.2130915   2.0263174   2.8640244  -1.8820466  -4.939141  ]
 [ 0.35244864  0.70300007  0.00707547  0.39383572  1.6902096 ]
 [ 0.6197723   1.2657262  -1.8316272  -1.3207386  -1.0917473 ]]


In [27]:
A = a * b
B = tf.scalar_mul(2, A)
C = tf.div(a,b)
D = tf.mod(a,b)

In [28]:
init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op)
    writer = tf.summary.FileWriter('graphs', sess.graph)
    a, b, A_R, B_R, C_R, D_R = sess.run([a, b, A, B, C, D])
    print("a\n", a, "\nb\n", b,  "a*b\n", A_R, "\n2*a*b\n", B_R, "\na/b\n",
         C_R, "\na%b\n", D_R)

a
 [[-4.954532   -1.2449592   2.888166   -3.5919921  -1.9026239 ]
 [-1.4724357  -1.8787607   2.2793992  -0.34695882  1.3522847 ]
 [-2.2130003  -0.71623474 -3.8966668  -3.4783466   0.97097915]
 [ 2.7822685  -0.84124136  1.4930949   5.570876   -0.1353087 ]] 
b
 [[ 0.44284907 -0.11315033 -0.40395573 -3.175851    3.6219687 ]
 [-4.0229316   0.8264399  -3.8547635   1.5784178   0.89475006]
 [ 2.412165   -1.0281409  -3.0972712   1.095942   -0.9303144 ]
 [ 3.3206313  -0.6548326   0.48197147 -5.797706    0.52647734]] a*b
 [[ -2.19411      0.14086755  -1.1666912   11.407632    -6.8912444 ]
 [  5.923508    -1.5526829   -8.786545    -0.547646     1.2099568 ]
 [ -5.338122     0.73639023  12.069034    -3.812066    -0.9033159 ]
 [  9.238888     0.55087227   0.71962917 -32.2983      -0.07123696]] 
2*a*b
 [[ -4.38822      0.2817351   -2.3333824   22.815264   -13.782489  ]
 [ 11.847016    -3.1053658  -17.57309     -1.095292     2.4199135 ]
 [-10.676244     1.4727805   24.138067    -7.624132    -1.8066318

In [29]:
writer.close()